set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property PACKAGE_PIN AM19 [get_ports {ddr4_rtl_0_dm_n[8]}]
set_property PACKAGE_PIN AW9 [get_ports {ddr4_rtl_0_dm_n[7]}]
set_property PACKAGE_PIN AY12 [get_ports {ddr4_rtl_0_dm_n[6]}]
set_property PACKAGE_PIN AR13 [get_ports {ddr4_rtl_0_dm_n[5]}]
set_property PACKAGE_PIN AY17 [get_ports {ddr4_rtl_0_dm_n[4]}]
set_property PACKAGE_PIN AU28 [get_ports {ddr4_rtl_0_dqs_t[2]}]
set_property PACKAGE_PIN BA26 [get_ports {ddr4_rtl_0_dqs_t[4]}]
set_property PACKAGE_PIN AU13 [get_ports {ddr4_rtl_0_dqs_t[6]}]
set_property PACKAGE_PIN AK20 [get_ports {ddr4_rtl_0_dqs_t[8]}]
set_property PACKAGE_PIN AR23 [get_ports {ddr4_rtl_0_dm_n[3]}]
set_property PACKAGE_PIN AW24 [get_ports {ddr4_rtl_0_dm_n[2]}]
set_property PACKAGE_PIN AR27 [get_ports {ddr4_rtl_0_dm_n[0]}]
set_property PACKAGE_PIN AR27 [get_ports {ddr4_rtl_0_dqs_t[1]}]
set_property PACKAGE_PIN AU24 [get_ports {ddr4_rtl_0_dm_n[1]}]

set_property PACKAGE_PIN AW24 [get_ports {ddr4_rtl_0_dqs_t[5]}]
set_property PACKAGE_PIN AM23 [get_ports {ddr4_rtl_0_dqs_t[6]}]
set_property PACKAGE_PIN AR23 [get_ports {ddr4_rtl_0_dqs_t[7]}]
set_property PACKAGE_PIN BA15 [get_ports {ddr4_rtl_0_dqs_t[8]}]